export { default as FormComponent } from './form/FormComponent'
export { default as MainHeading } from './typography/MainHeading'
export { default as Heading } from './typography/Heading'
export { default as Navbar } from './navbar/Navbar'
export { default as FileView } from './page/FileView'
export { default as FolderView } from './page/FolderView'
