'use client'

import './globals.css'
import { DM_Sans } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'
// import { Navbar } from '@/app/components'
import theme from './theme/theme'

const DMSans = DM_Sans({
  weight: ['400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1,minimum-scale=1"
      />
      <body className={DMSans.className}>
        <ThemeProvider theme={theme}>
          {/* <Navbar /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
