import { File, FileDoc, FileWord } from '../../assets'

export const fileData = [
  {
    name: 'Java language...',
    fileType: 'pdf',
    FileLogo: File,
    language: 'English',
    percentage: 50,
  },
  {
    name: 'Java programming',
    fileType: 'doc',
    FileLogo: FileDoc,
    language: 'English',
    percentage: 80,
  },
  {
    name: 'Cobol program',
    fileType: 'word',
    FileLogo: File,
    language: 'Kannada',
    percentage: 10,
  },
  {
    name: 'Thesis evaluvation',
    fileType: 'pdf',
    FileLogo: FileWord,
    language: 'Tamil',
    percentage: 18,
  },
  {
    name: 'Drill plagiarism',
    fileType: 'doc',
    FileLogo: File,
    language: 'Telugu',
    percentage: 80,
  },
  {
    name: 'Cobol program',
    fileType: 'word',
    FileLogo: File,
    language: 'Kannada',
    percentage: 10,
  },
  {
    name: 'Thesis evaluvation',
    fileType: 'pdf',
    FileLogo: FileWord,
    language: 'Tamil',
    percentage: 18,
  },
  {
    name: 'Drill plagiarism',
    fileType: 'doc',
    FileLogo: File,
    language: 'Telugu',
    percentage: 80,
  },
  {
    name: 'Cobol program',
    fileType: 'word',
    FileLogo: File,
    language: 'Kannada',
    percentage: 10,
  },
  {
    name: 'Thesis evaluvation',
    fileType: 'pdf',
    FileLogo: FileWord,
    language: 'Tamil',
    percentage: 18,
  },
  {
    name: 'Drill plagiarism',
    fileType: 'doc',
    FileLogo: File,
    language: 'Telugu',
    percentage: 80,
  },
  {
    name: 'Cobol program',
    fileType: 'word',
    FileLogo: File,
    language: 'Kannada',
    percentage: 10,
  },
  {
    name: 'Thesis evaluvation',
    fileType: 'pdf',
    FileLogo: FileWord,
    language: 'Tamil',
    percentage: 18,
  },
]
